# Generated by Django 2.2.1 on 2019-06-03 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoryItem',
            new_name='History',
        ),
    ]
