# Generated by Django 3.1.1 on 2021-05-09 01:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0002_auto_20190603_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
