# Generated by Django 3.1.1 on 2021-05-09 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0003_history_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='creation_date',
        ),
    ]
