# Generated by Django 3.1.1 on 2021-05-09 01:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0004_remove_history_creation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'get_latest_by': 'creation_date'},
        ),
        migrations.AddField(
            model_name='history',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
